# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 08:53
from __future__ import unicode_literals

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageExampleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Name')),
                ('image', versatileimagefield.fields.VersatileImageField(height_field='height', upload_to='images/testimagemodel/', verbose_name='Image', width_field='width')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='Image Height')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='Image Width')),
                ('optional_image', versatileimagefield.fields.VersatileImageField(blank=True, upload_to='images/testimagemodel/optional/', verbose_name='Optional Image')),
            ],
            options={
                'verbose_name': 'Image Example',
                'verbose_name_plural': 'Image Examples',
            },
        ),
    ]
